
SELECT CONVERT(VARCHAR(23), GETDATE(), 121);

SELECT * FROM TABELA_DE_CLIENTES;

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(23), DATA_DE_NASCIMENTO, 121)
FROM TABELA_DE_CLIENTES;

SELECT DATA_DE_NASCIMENTO, CONVERT(VARCHAR(23), DATA_DE_NASCIMENTO, 106)
FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, ROUND(PRECO_DE_LISTA,2) AS PRECO_DE_LISTA
FROM TABELA_DE_PRODUTOS;

-- conversão implícita
SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: ', PRECO_DE_LISTA) AS PRECO
FROM TABELA_DE_PRODUTOS;

-- conversão explícita com o CAST
SELECT NOME_DO_PRODUTO, CONCAT('O preço de lista é: ', CAST(PRECO_DE_LISTA AS VARCHAR(10))) AS PRECO
FROM TABELA_DE_PRODUTOS;

/*Queremos construir um SQL cujo resultado seja para cada cliente:

"O cliente João da Silva comprou R$ 121222,12 no ano de 2016".
Faça isso somente para o ano de 2016.

Dica: Procure na documentação como se usa a função STR para converter um número FLOAT em texto.*/

SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM NOTAS_FISCAIS;

SELECT
C.NOME, CONCAT('O cliente ', C.NOME, 'comprou R$ ', TRIM(STR(SUM(I.QUANTIDADE * I.PRECO),10,2)),
' no ano de ', YEAR(N.DATA_VENDA),'.') AS VALOR
FROM NOTAS_FISCAIS AS N
INNER JOIN ITENS_NOTAS_FISCAIS AS I ON I.NUMERO = N.NUMERO
INNER JOIN TABELA_DE_CLIENTES AS C ON C.CPF = N.CPF
WHERE YEAR(DATA_VENDA) = '2016'
GROUP BY C.NOME, YEAR(DATA_VENDA);