
-- Média do preço de listas por embalagem:

SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

-- Usando HAVING:
SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
HAVING AVG(PRECO_DE_LISTA) <=10;

-- Usando Subquery:
SELECT MEDIA_EMBALAGENS.EMBALAGEM, MEDIA_EMBALAGENS.PRECO_MEDIO
FROM (SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
	  FROM TABELA_DE_PRODUTOS
	  GROUP BY EMBALAGEM) MEDIA_EMBALAGENS
WHERE MEDIA_EMBALAGENS.PRECO_MEDIO <= 10;


SELECT SOMA_QUANTIDADE.CODIGO_DO_PRODUTO, SOMA_QUANTIDADE.QUANTIDADE, SOMA_QUANTIDADE.NOME_DO_PRODUTO
FROM (SELECT INF.CODIGO_DO_PRODUTO,TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
	  FROM ITENS_NOTAS_FISCAIS  INF
	  INNER JOIN TABELA_DE_PRODUTOS TP 
	  ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
      GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO) SOMA_QUANTIDADE
WHERE SOMA_QUANTIDADE.QUANTIDADE > 394000
ORDER BY SOMA_QUANTIDADE.QUANTIDADE DESC;



