
--Quais são os clientes localizados nos bairros que existem vencedores?

SELECT COUNT(*) FROM TABELA_DE_CLIENTES;
-- 16 CLIENTES ---> 7 CLIENTES POSSUEM NOS VENDEDORES NOS SEUS BAIRROS

SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;
-- 4 VENDEDORES ---> 3 VENDEDORES POSSUEM CLIENTES NOS SEUS BAIRROS

SELECT DISTINCT
V.NOME AS NOME_DO_VENDEDOR,
V.BAIRRO AS BAIRRO_DO_VENDEDOR,
C.BAIRRO AS BAIRRO_DO_CLIENTE,
C.NOME	 AS NOME_DO_CLIENTE
FROM TABELA_DE_CLIENTES C
INNER JOIN TABELA_DE_VENDEDORES V ON C.BAIRRO = V.BAIRRO;

-- Qual é o vendedor que não tem cliente no seu bairro? --> Resp.: Roberta Martins em Copacabana.
SELECT DISTINCT
V.NOME AS NOME_DO_VENDEDOR,
V.BAIRRO AS BAIRRO_DO_VENDEDOR,
C.BAIRRO AS BAIRRO_DO_CLIENTE,
C.NOME	 AS NOME_DO_CLIENTE
FROM TABELA_DE_CLIENTES C
RIGHT JOIN TABELA_DE_VENDEDORES V ON C.BAIRRO = V.BAIRRO
WHERE C.BAIRRO IS NULL;

-- Quais os clientes que moram em bairros que não possuem vendedores? 
SELECT DISTINCT
V.NOME AS NOME_DO_VENDEDOR,
V.BAIRRO AS BAIRRO_DO_VENDEDOR,
C.BAIRRO AS BAIRRO_DO_CLIENTE,
C.NOME	 AS NOME_DO_CLIENTE
FROM TABELA_DE_CLIENTES C
LEFT JOIN TABELA_DE_VENDEDORES V ON C.BAIRRO = V.BAIRRO
WHERE V.BAIRRO IS NULL;

-- Resp.: 9 clientes não possuem vencedores em seus bairros:
/*Fernando Cavalcante
Juliana Silva
Fabio Carvalho
Marcelo Mattos
Edson Meilelles
Abel Silva 
Marcos Nogueira
Petra Oliveira
Walber Lontra*/

-- Para responder as duas perguntas em uma única consulta, podemos utilizar o FULL JOIN:
SELECT DISTINCT
V.NOME AS NOME_DO_VENDEDOR,
V.BAIRRO AS BAIRRO_DO_VENDEDOR,
C.BAIRRO AS BAIRRO_DO_CLIENTE,
C.NOME	 AS NOME_DO_CLIENTE
FROM TABELA_DE_CLIENTES C
FULL JOIN TABELA_DE_VENDEDORES V ON C.BAIRRO = V.BAIRRO;
