
SELECT * FROM TABELA_DE_CLIENTES;

-- Transformando os nomes em letras minúsculas:
SELECT NOME, LOWER(NOME) AS NOME_MINUSCULO
FROM TABELA_DE_CLIENTES;

-- Transformando os nomes em letras maiúsculas:
SELECT NOME, UPPER(NOME) AS NOME_MAIUSCULO
FROM TABELA_DE_CLIENTES;

-- Concatenando nomes que estão em colunas separadas:
SELECT NOME, CONCAT(ENDERECO_1, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO,' ', '-',' ', CEP) AS ENDERECO_COMPLETO
FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_PRODUTOS;

-- Exibindo as 3 primeiras letras:
SELECT NOME_DO_PRODUTO, LEFT(NOME_DO_PRODUTO,3) AS NOME_CURTO_PRODUTO
FROM TABELA_DE_PRODUTOS;

-- Exibindo as 3 últimas letras:
SELECT NOME_DO_PRODUTO, RIGHT(NOME_DO_PRODUTO,3) AS NOME_CURTO_PRODUTO
FROM TABELA_DE_PRODUTOS;

-- Substituir Litro e Litros para L:
SELECT TAMANHO, REPLACE(REPLACE(TAMANHO, 'Litros', 'L'), 'Litro','L') AS TAMANHO_MODIFICADO
FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_CLIENTES;

--Trazer apenas o primeiro nome dos clientes:

SELECT NOME, CHARINDEX(' ', NOME, 1) 
FROM TABELA_DE_CLIENTES;

SELECT NOME, SUBSTRING(NOME, 1, CHARINDEX(' ', NOME, 1)) AS PRIMEIRO_NOME
FROM TABELA_DE_CLIENTES;