SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR in ('Lima/Limao', 'Morango/Limao');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Limao';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Maca%';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE 'Morango%';

SELECT * FROM TABELA_DE_PRODUTOS WHERE (SABOR LIKE 'Morango%') AND (EMBALAGEM = 'PET');

SELECT *
FROM TABELA_DE_CLIENTES 
WHERE NOME LIKE '%Silva%';

--- Utilizando o DISTINCT para não retornar os valores duplicados
SELECT DISTINCT SABOR
FROM TABELA_DE_PRODUTOS;

-- DISTINCT TOP: Mostra as primeiras linhas de uma tabela muito grande
SELECT TOP 4 *
FROM TABELA_DE_CLIENTES;

/*Tendo em vista os conteúdos trabalhados em aula,
qual é o comando SQL para listar as 10 primeiras vendas do dia 01/10/2017?*/

SELECT TOP 10 * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '2017/10/01';

-- Ordenando a saída do resultado (ORDER BY)

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY NOME_DO_PRODUTO;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM, NOME_DO_PRODUTO;

SELECT TOP 5* FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;

--Qual foi a maior venda do produto "Linha Refrescante - 1 Litro - Morango/Limao" em quantidade?

SELECT *
FROM TABELA_DE_PRODUTOS
WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao';

'1101035'

SELECT *
FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = '1101035'
ORDER BY QUANTIDADE DESC;












