SELECT *
FROM TABELA_DE_CLIENTES;

SELECT CPF, NOME, BAIRRO, CIDADE
FROM TABELA_DE_CLIENTES;

SELECT NOME, CPF, BAIRRO, CIDADE
FROM TABELA_DE_CLIENTES;

--- Utilizando o alias para renomear colunas
SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DO CLIENTE], BAIRRO, CIDADE
FROM TABELA_DE_CLIENTES;

SELECT * 
FROM TABELA_DE_PRODUTOS
WHERE CODIGO_DO_PRODUTO = '290478';

SELECT *
FROM TABELA_DE_CLIENTES
WHERE IDADE > 20;